export const TelemetryEvents = {
  ACTIVE_STATE_ROUTING: "ACTIVE_STATE_ROUTING",
  STATE_CONFLICT_RESOLVED: "STATE_CONFLICT_RESOLVED",
  STATE_MICRO_INTENT: "STATE_MICRO_INTENT",
  SAFE_INTENT_CONSUMED: "SAFE_INTENT_CONSUMED",
  STATE_GUIDANCE_LEVEL: "STATE_GUIDANCE_LEVEL",
  CONV_AI_REQUESTED: "CONV_AI_REQUESTED",
  CONV_AI_SKIPPED: "CONV_AI_SKIPPED",
  CONV_AI_VALIDATED: "CONV_AI_VALIDATED",
  CONV_AI_REJECTED: "CONV_AI_REJECTED",
  CONV_AI_FALLBACK: "CONV_AI_FALLBACK",
  CONV_COST: "CONV_COST",
  EDGE_GATE_ACTION: "EDGE_GATE_ACTION",
  DUPLICATE_SUPPRESSED: "DUPLICATE_SUPPRESSED",
  NONSCAN_REPLY_SENT: "NONSCAN_REPLY_SENT",
};

/**
 * @param {string} event
 * @param {Record<string, unknown>} payload
 */
export function logTelemetryEvent(event, payload = {}) {
  console.log(JSON.stringify({ event, ...payload }));
}
