export const TelemetryEvents = {
  ACTIVE_STATE_ROUTING: "ACTIVE_STATE_ROUTING",
  STATE_CONFLICT_RESOLVED: "STATE_CONFLICT_RESOLVED",
  STATE_MICRO_INTENT: "STATE_MICRO_INTENT",
  SAFE_INTENT_CONSUMED: "SAFE_INTENT_CONSUMED",
  STATE_GUIDANCE_LEVEL: "STATE_GUIDANCE_LEVEL",
  CONV_AI_REQUESTED: "CONV_AI_REQUESTED",
  CONV_AI_SKIPPED: "CONV_AI_SKIPPED",
  CONV_AI_VALIDATED: "CONV_AI_VALIDATED",
  CONV_AI_REJECTED: "CONV_AI_REJECTED",
  CONV_AI_FALLBACK: "CONV_AI_FALLBACK",
  CONV_COST: "CONV_COST",
  EDGE_GATE_ACTION: "EDGE_GATE_ACTION",
  DUPLICATE_SUPPRESSED: "DUPLICATE_SUPPRESSED",
  NONSCAN_REPLY_SENT: "NONSCAN_REPLY_SENT",
  /** Deterministic routing / UX fallback (e.g. conv AI rejected). */
  STATE_FALLBACK_REASON: "STATE_FALLBACK_REASON",
  STATE_NO_PROGRESS_STREAK: "STATE_NO_PROGRESS_STREAK",
  NONSCAN_REPLY_GATEWAY_PAYMENT_QR: "NONSCAN_REPLY_GATEWAY_PAYMENT_QR",
  NONSCAN_GATEWAY_PUSH: "NONSCAN_GATEWAY_PUSH",
};

/**
 * @param {string} event
 * @param {Record<string, unknown>} payload
 */
export function logTelemetryEvent(event, payload = {}) {
  console.log(JSON.stringify({ event, ...payload }));
}
