-- Disable Row Level Security on all app tables.
-- Required for local PostgreSQL setup (PostgREST with web_anon role).
-- Supabase cloud uses RLS + service_role; local uses direct grants without RLS.

ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_state DISABLE ROW LEVEL SECURITY;
ALTER TABLE energy_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE energy_copy_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE footage_clips DISABLE ROW LEVEL SECURITY;
ALTER TABLE line_conversation_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE object_family_category_map DISABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE persona_ab_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE persona_ab_funnel_daily DISABLE ROW LEVEL SECURITY;
ALTER TABLE persona_ab_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE persona_ab_weights DISABLE ROW LEVEL SECURITY;
ALTER TABLE report_publications DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_public_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_result_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_results_v2 DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_uploads DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_entitlements DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_job_visual_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_pipeline_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE visual_assets DISABLE ROW LEVEL SECURITY;
